checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*

build:
  environment:
    php:
      version: '7.2'
    variables:
      ELASTICSEARCH_HOST=localhost:9200
  nodes:
    services:
      elasticsearch: 6.6.2
    analysis:
      tests:
        override:
          - php-scrutinizer-run
            command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
            coverage:
              file: 'coverage.clover'
              format: 'clover'