language: php

global:
  - ELASTICSEARCH_HOST=localhost:9200
  
env:
  - ELASTICSEARCH_BUILD=6.6.2.deb
  - ELASTICSEARCH_BUILD=7.1.1-amd64.deb
  
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
  
cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  allow_failures:
    - php: nightly
    - env: ELASTICSEARCH_VERSION=7.1.1

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ELASTICSEARCH_BUILD && sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_BUILD && sudo service elasticsearch restart
  - sleep 20
  - curl -X GET "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest --prefer-source
script:
  - vendor/bin/phpunit --testdox
  - vendor/bin/phpstan analyse
