language: php

env:
  - ELASTICSEARCH_HOST=localhost:9200

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  - ELASTICSEARCH_VERSION=6.6.2
  - ELASTICSEARCH_VERSION=7.1.1
cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  allow_failures:
    - php: nightly
    - env: ELASTICSEARCH_VERSION=7.1.1

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ELASTICSEARCH_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb && sudo service elasticsearch restart
  - sleep 20
  - curl -X GET "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest --prefer-source
script:
  - vendor/bin/phpunit --testdox
  - vendor/bin/phpstan analyse
