language: php

services:
  - elasticsearch

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
  - "$HOME/.composer/cache/files"

matrix:
  allow_failures:
    - php: nightly

before_script:
    - sleep 10
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --no-suggest --prefer-source
script:
    - vendor/bin/phpunit --testdox
    - vendor/bin/phpstan analyse
